/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/public/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicArticle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminArticles"];
        put?: never;
        post: operations["createAdminArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getAdminArticle"];
        put: operations["updateAdminArticle"];
        post?: never;
        delete: operations["deleteAdminArticle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminCategories"];
        put?: never;
        post: operations["createAdminCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getAdminCategory"];
        put: operations["updateAdminCategory"];
        post?: never;
        delete: operations["deleteAdminCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminTags"];
        put?: never;
        post: operations["createAdminTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getAdminTag"];
        put: operations["updateAdminTag"];
        post?: never;
        delete: operations["deleteAdminTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSession"];
        put?: never;
        post: operations["loginAdmin"];
        delete: operations["logoutAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SiteResponse: {
            title: string;
            description: string;
        };
        ArticleSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            excerpt?: string | null;
            /** Format: date-time */
            publishedAt: string;
        };
        ArticleListResponse: {
            items: components["schemas"]["ArticleSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            total: number;
        };
        ArticleResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            excerpt?: string | null;
            /** Format: date-time */
            publishedAt: string;
            markdown: string;
        };
        ProblemResponse: {
            code: string;
            title: string;
            detail: string;
            traceId: string;
        };
        AdminLoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        AdminSessionResponse: {
            username: string;
            /** @enum {string} */
            role: "ADMIN";
            authenticated: boolean;
        };
        CsrfTokenResponse: {
            token: string;
        };
        /** @enum {string} */
        ArticleStatus: "DRAFT" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
        AdminArticleCreateRequest: {
            slug?: string | null;
            title?: string | null;
            excerpt?: string | null;
            markdown?: string;
            seoTitle?: string | null;
            seoDescription?: string | null;
            /** Format: date-time */
            scheduledAt?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            coverMediaId?: string | null;
            tagIds?: string[];
        };
        AdminArticleUpdateRequest: {
            /** Format: int64 */
            version: number;
            slug?: string | null;
            title: string;
            excerpt?: string | null;
            markdown: string;
            seoTitle?: string | null;
            seoDescription?: string | null;
            /** Format: date-time */
            scheduledAt?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            coverMediaId?: string | null;
            tagIds?: string[];
        };
        AdminArticleSummary: {
            /** Format: uuid */
            id: string;
            slug?: string | null;
            title: string;
            status: components["schemas"]["ArticleStatus"];
            /** Format: uuid */
            categoryId: string | null;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        AdminArticleListResponse: {
            items: components["schemas"]["AdminArticleSummary"][];
            page: number;
            size: number;
            /** Format: int64 */
            total: number;
        };
        AdminArticleResponse: {
            /** Format: uuid */
            id: string;
            slug?: string | null;
            title: string;
            excerpt?: string | null;
            markdown: string;
            status: components["schemas"]["ArticleStatus"];
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            scheduledAt?: string | null;
            seoTitle?: string | null;
            seoDescription?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            /** Format: uuid */
            coverMediaId?: string | null;
            tagIds: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        CategoryRequest: {
            name: string;
            slug: string;
            description?: string | null;
            sortOrder?: number;
        };
        CategoryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            sortOrder: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TagRequest: {
            name: string;
            slug: string;
        };
        TagResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Internal error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Public article not found */
        ArticleNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Resource not found */
        ResourceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Request conflicts with current resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Authentication required */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Access denied */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Invalid CSRF token */
        CsrfInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Invalid administrator credentials */
        AuthenticationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
        /** @description Login attempts from this source are temporarily rate limited */
        LoginRateLimited: {
            headers: {
                /** @description Seconds until another login attempt may be tried */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemResponse"];
            };
        };
    };
    parameters: {
        CsrfHeader: string;
        IfNoneMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Entity tag for the public representation */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPublicSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listPublicArticles: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: {
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published articles */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleListResponse"];
                };
            };
            /** @description Public article list representation has not changed */
            304: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getPublicArticle: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published article detail */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponse"];
                };
            };
            /** @description Public article representation has not changed */
            304: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["ArticleNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAdminArticles: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                status?: components["schemas"]["ArticleStatus"];
                keyword?: string;
                direction?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator article list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticleListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminArticle: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdminArticleCreateRequest"];
            };
        };
        responses: {
            /** @description Draft created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getAdminArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticleResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    updateAdminArticle: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminArticleUpdateRequest"];
            };
        };
        responses: {
            /** @description Article updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteAdminArticle: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticleResponse"];
                };
            };
            /** @description Draft physically deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    listAdminCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminCategory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            409: components["responses"]["Conflict"];
        };
    };
    getAdminCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    updateAdminCategory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteAdminCategory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAdminTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminTag: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description Tag created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            409: components["responses"]["Conflict"];
        };
    };
    getAdminTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ResourceNotFound"];
        };
    };
    updateAdminTag: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description Tag updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteAdminTag: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
            404: components["responses"]["ResourceNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current administrator session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    loginAdmin: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Administrator session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthenticationFailed"];
            403: components["responses"]["CsrfInvalid"];
            429: components["responses"]["LoginRateLimited"];
        };
    };
    logoutAdmin: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-TOKEN": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfInvalid"];
        };
    };
    getAdminCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token for administrator write requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
        };
    };
}
